services:
 backend:
   build: ./backend
   env_file: ./backend/.env
   environment:
     AZURE_OPENAI_ENDPOINT: $${AZURE_OPENAI_ENDPOINT}
     AZURE_OPENAI_KEY: $${AZURE_OPENAI_KEY}
     AZURE_OPENAI_DEPLOYMENT: $${AZURE_OPENAI_DEPLOYMENT}
