name: Build and deploy Python app to Azure Web App - cwfinanceanalyticalcompanion

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: cwfinanceanalyticalcompanion
  PACKAGE_PATH: backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # (Optional) If you run tests, set working-directory to backend
      # - uses: actions/setup-python@v5
      #   with: { python-version: '3.11' }
      # - run: pip install -r requirements.txt && pytest
      #   working-directory: backend

      - name: Upload backend as artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-src
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: backend-src
          path: backend

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBDCB9C699E549748A782D21C11457B0 }}
          package: backend
