# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - cwfinanceanalyticalcompanion

on:
  push:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yml
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: cwfinanceanalyticalcompanion   # your app name
  AZURE_WEBAPP_PACKAGE_PATH: backend                # <— subfolder to deploy
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: backend
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cwfinanceanalyticalcompanion'
          slot-name: 'Production'

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBDCB9C699E549748A782D21C11457B0 }}

